<html>
<head>
<style>
#error_block {
    color: red;

}
#result_block {
    color: green;
    font-size: 35px;
}
.entries {
    display: inline;
    font-size: 15px;
}

#quantity_of_operations {
    display: none;
}
#quantity_of_currencies {
    display: none;
}

</style>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
     <script defer src="/app/Content/external_files/js_functions.js"></script>

<script> 


    
  </script>

<title>Currency converter</title>
</head>

<body>
